#!/bin/bash

PARAM=${1:-alias}

TMP_FILE=/tmp/git-list.tmp

git config --show-origin --get-regexp ^${PARAM}\\. | sed -E 's|^file:||g' > ${TMP_FILE} 

cat ${TMP_FILE} | awk '{print $1}' | uniq > ${TMP_FILE}.envs

if [ -n "$(cat ${TMP_FILE})" ]; then
	echo "Printing all Git configurations for section [${PARAM}]"
	echo
else
	echo "No configurations found under [${PARAM}]"
	exit 1
fi

while read TMP_ENV; do
	if [ "${TMP_ENV}" = "${HOME}/.gitconfig" ]; then
		echo "[GLOBAL - ${TMP_ENV}]"
	elif [ "${TMP_ENV}" = ".git/config" ]; then
		echo "[LOCAL - ${TMP_ENV}]"
	else
		echo "[${TMP_ENV}]"
	fi
	cat ${TMP_FILE} | grep "${TMP_ENV}" | sed -E 's|^'${TMP_ENV}'.'${PARAM}'\.([^ ]+) (.*)|    \1  =  \2|g'
	echo
done < ${TMP_FILE}.envs
